### PR TITLE
delete aws again ^.^

### PR DESCRIPTION
**Pull request by fidel-bello**

### CODE REVIEW

**Review by anthony-fdez — APPROVED** [review]
Nice lol. I see this happening a couple more times hahaha

**Comment by fidel-bello** [comment]
Screenshot 2022-10-04 124147

**Comment by fidel-bello** [comment]
check it out thooo

**Comment by anthony-fdez** [comment]
Oh shiiii bro you learn quick!

**Comment by fidel-bello** [comment]
@anthony-fdez  hahaha!! ya tu sabe

**Pull request merged**
